### ISSUE TITLE
Knowledge Base问题

### ISSUE THREAD

**Issue by sujiaqi-1** [China-UK-ZSL/ZS-F-VQA#10]
你好，我在阅读代码过程中发现你所检索的Knowledge Base好像不是包含 193,449个fact的Knowledge Base，而是每个问题所对应的fact组成的Knowledge Base, 我想确认一下这样是可以的吗

**Comment by hackerchenzhuo** [comment]
同学你好：

在训练过程中使用问题所对应的fact组成的Knowledge Base，测试的时候是可以在193,449个fact的Knowledge Base中进行的。

因为很多实体在训练中未见过，因此不会有预测bias，最终的召回效果应该是接近的，你可以试一下

**Comment by sujiaqi-1** [comment]
好的，谢谢！
