### ISSUE TITLE
how to evaluate my own data

### ISSUE THREAD

**Issue by wz1211** [China-UK-ZSL/ZS-F-VQA#11]
Thanks for your paper and shared codes!
I'm new at this area . I wonder how to evaluate my own data(input an image and a question , then get an answer) by establishing an API

**Comment by hackerchenzhuo** [comment]
Thanks for your comments.

- For evaluation:
Please simply refer to the [evaluation script](https://github.com/China-UK-ZSL/ZS-F-VQA/blob/main/code/run_ZSL.sh) and modify the relevant test code.

- For your own data:
**Question**: code for [process answer vocab](https://github.com/hexiang-hu/answer_embedding/blob/master/tools/preprocess_answer.py) and [process questions vocab](https://github.com/hexiang-hu/answer_embedding/blob/master/tools/preprocess_question.py)
**Image**:  you could generate a pretrained image feature  via this way ([Guidance](https://github.com/hexiang-hu/answer_embedding/issues/3) / [code](https://github.com/Cyanogenoid/pytorch-vqa/blob/master/preprocess-images.py))

- Please  refer to the **Usage** in Readme.

**Comment by agui1213** [comment]
Thank u
but how can I get the answer(str , not a tensor)

**Comment by hackerchenzhuo** [comment]
The program should have generated answer mappings (such as IDs or indexes) during the running progress. 
Maybe you can slightly modify the evaluation part of the code to extract them (i.e., mappings) manually and output their corresponding surfaces.

It's been a long time, I forgot part of the exact details.
