### ISSUE TITLE
For data check:

### ISSUE THREAD

**Issue by ghost** [China-UK-ZSL/ZS-F-VQA#13]
你好，我现在在使用自己的数据集进行训练，我按照您项目中的json文件标注的问题答案以及对应的fact。
但是我想知道数据检查部分是什么用途，项目中有很多filter文件，我自己的数据集需要怎么做呢

**Comment by hackerchenzhuo** [comment]
感谢你对该工作的关注

数据检查应该是对于row data进行数据清洗的一个过程，主要包括知识三元组和vqa问答pair的处理，涉及到一个Knowledge group的过程，也涉及到VQA社区中比喻基于word/answer occurance相关的筛选（比如去掉长尾answer）。相关内容你可以酌情参考，应该也有很多其他的vqa工作是类似的做法

祝好🤞🏻

**Comment by ghost** [comment]
感谢您这么快回复！


按照您的解释，我是不是可以理解为，我可以跳过这一步操作呢，直接用common_data文件夹里标注的文本json文件和图像h5文件就可以直接训练和测试。
因为我在自己数据集上尝试的数据检查，但是没有任何反应，我一直没找到原因，所以想知道是否能跳过这一步骤。


祝好！

**Comment by hackerchenzhuo** [comment]
理论上是的。

但是数据集里面的一些噪音可能会干扰实验结果导致对比过程偏低。

如果只是做测试用也是ok的
