### ISSUE TITLE
fvqa-resnet-14x14.h5

### ISSUE THREAD

**Issue by applegirls250** [China-UK-ZSL/ZS-F-VQA#2]
Hello, I try to reproduce your code, but I don’t know how to generate fvqa-resnet-14x14.h5. Can you share this file with me, thank you very much

**Comment by hackerchenzhuo** [comment]
Thanks for your advise :) I will update this part of the code recently.

**Comment by hackerchenzhuo** [comment]
@applegirls250  Hi, the pretrained `fvqa-resnet-14x14.h5` now is available in `README` file :)
