### ISSUE TITLE
你好能不能提供原始的COCO和ImageNet的images呢，有没有连接可以给一下谢谢

### ISSUE THREAD

**Issue by Einstones** [China-UK-ZSL/ZS-F-VQA#3]

**Comment by hackerchenzhuo** [comment]
有的，在FVQA原项目[FVQA](https://github.com/wangpengnorman/FVQA)中的[download_link](https://www.dropbox.com/s/iyz6l7jhbt6jb7q/new_dataset_release.zip?dl=0)。其中的new_dataset_release部分。

感谢提醒，已经更新到readme了
