### ISSUE TITLE
fvqa_36.hdf5 and fvqa36_imgid2idx.pkl

### ISSUE THREAD

**Issue by applegirls250** [China-UK-ZSL/ZS-F-VQA#4]
Dear scholar, Could you provide your fvqa_36.hdf5 and fvqa36_imgid2idx.pkl?

**Comment by hackerchenzhuo** [comment]
Sorry for the late reply.

The original cache file has been lost since our machine was reset once, which wiped out all these data.

Maybe you could follow this two projects for more details:
https://github.com/jwyang/faster-rcnn.pytorch
https://github.com/wangpengnorman/FVQA
