### ISSUE TITLE
the feature file for the BUTD or the BAN model

### ISSUE THREAD

**Issue by runzeer** [China-UK-ZSL/ZS-F-VQA#5]
Dear Prof:
     Could you please tell me how to get the feature file for the BUTD or the BAN model?

**Comment by hackerchenzhuo** [comment]
Thanks for your question.

maybe you could generate the feature from BUTD or the BAN model  from:
https://github.com/jnhwkim/ban-vqa
https://github.com/hengyuan-hu/bottom-up-attention-vqa
