### ISSUE TITLE
How can I get the predicted answer of each ‘image-question’ pair?

### ISSUE THREAD

**Issue by lmhlll** [China-UK-ZSL/ZS-F-VQA#6]
Hi, now I can complet the eval, but I also want to get the predicted answer file. Looking forward to your reply！

**Comment by hackerchenzhuo** [comment]
Thanks for your attention.

Maybe you could try to export the answer from this line:
https://github.com/China-UK-ZSL/ZS-F-VQA/blob/a66f75dfac361860ef0e08c6a74d2e91196ea929/code/main.py#L240
