### ISSUE TITLE
图片

### ISSUE THREAD

**Issue by Lily11223344** [China-UK-ZSL/ZS-F-VQA#7]
请问图片直接下载您给的FVQA放在 data/KG_VQA/fvqa/exp_data/images/images文件下，可以直接运行代码吗？

个人感觉您写的README逻辑不够清晰，您能写的清楚点嘛？

**Comment by hackerchenzhuo** [comment]
同学你好。FVQA原始图像是没有Feature信息的，你可以下载抽取的特征信息放在对应目录：
Image feature: fvqa-resnet-14x14.h5 pretrained: [GoogleDrive](https://drive.google.com/file/d/1YG9hByw01_ZQ6_mKwehYiddG3x2Cxatu/view?usp=sharing) or [BaiduCloud](https://pan.baidu.com/s/1ks84AWSXxJJ_7LwnzWdEnQ) (password:16vd)

有了特征信息的话理论上可以不需要图片信息。

**Comment by Lily11223344** [comment]
好的，谢谢您。
----&nbsp;原始邮件&nbsp;----
***@***.***&gt;;
Date:2022年6月15日(星期三)&nbsp;下午5:40
***@***.***&gt;;
***@***.******@***.***&gt;;
Subject:Re:&nbsp;[China-UK-ZSL/ZS-F-VQA]&nbsp;图片&nbsp;(Issue&nbsp;#7)



 
同学你好。FVQA原始图像是没有Feature信息的，你可以下载抽取的特征信息放在对应目录：
 Image feature: fvqa-resnet-14x14.h5 pretrained: GoogleDrive or BaiduCloud (password:16vd)
 
有了特征信息的话理论上可以不需要图片信息。
 
&mdash;
