### ISSUE TITLE
RuntimeError: Attempting to deserialize object on CUDA device 1 but torch.cuda.device_count() is 1.

### ISSUE THREAD

**Issue by ing907** [China-UK-ZSL/ZS-F-VQA#8]
Great work.

By the way, when i run _joint_test.py_ with another gpu you used, a run time error occurs.

`python joint_test.py --gpu_id 0 --exp_name fusion_prediction --ZSL 0 --exp_id rel3_fact10data_3score_10 --data_choice 3 --top_rel 3 --top_fact 10 --soft_score 10  --mrr 1`

Maybe you can simply change _line 336_ in _joint_test.py_ with below link
[https://stackoverflow.com/questions/53186736/](url)

**Comment by hackerchenzhuo** [comment]
Thanks for your suggestion, I have just added a tip before this line.
