### ISSUE TITLE
How to compute in parallel on two GPUs？

### ISSUE THREAD

**Issue by ZuoZicheng** [China-UK-ZSL/ZS-F-VQA#9]
Thanks for sharing the code, and I would like to know how to train this model on two GPUs?

**Comment by hackerchenzhuo** [comment]
Well, I think you can refer to this 

- https://www.run.ai/guides/multi-gpu/pytorch-multi-gpu-4-techniques-explained

- https://stackoverflow.com/questions/54216920/how-to-use-multiple-gpus-in-pytorch
